In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np

# to ignore the warnings
from warnings import filterwarnings

In [43]:
df = pd.read_csv('./data/nbaFeaturedEngineered.csv')
df

date  visitor_points  home_points  visitor_fgm  \
0     2018-01-01 00:00:00+00:00           114.0         96.0         41.0   
1     2018-01-01 00:00:00+00:00            98.0        106.0         36.0   
2     2018-01-01 00:00:00+00:00           142.0        148.0         53.0   
3     2018-01-01 00:00:00+00:00           116.0        113.0         46.0   
4     2018-01-01 01:00:00+00:00           123.0        110.0         43.0   
...                         ...             ...          ...          ...   
9505  2025-01-02 00:30:00+00:00           103.0        119.0         47.0   
9506  2025-01-02 00:30:00+00:00           113.0        130.0         52.0   
9507  2025-01-02 01:00:00+00:00            99.0        110.0         42.0   
9508  2025-01-02 02:00:00+00:00           120.0        139.0         53.0   
9509  2025-01-02 03:00:00+00:00           107.0        113.0         41.0   

      visitor_fga  visitor_fgp  visitor_ftm  visitor_fta  visitor_ftp  \
0            76.0        0.539         18.0         24.0        0.750   
1            93.0        0.387         15.0         19.0        0.789   
2           105.0        0.505         26.0         37.0        0.703   
3            89.0        0.517          9.0         14.0        0.643   
4            77.0        0.558         27.0         34.0        0.794   
...           ...          ...          ...          ...          ...   
9505         85.0        0.553         16.0         23.0        0.696   
9506         88.0        0.591         10.0         13.0        0.769   
9507         89.0        0.472         18.0         23.0        0.783   
9508         94.0        0.564         21.0         21.0        1.000   
9509         84.0        0.488         22.0         24.0        0.917   

      visitor_tpm  ...  visitor_ORtg   home_ORtg  visitor_DRtg   home_DRtg  \
0            14.0  ...    118.061309   95.049505     99.420050  112.871287   
1            11.0  ...     94.814241  108.295872    102.554180  100.122599   
2            10.0  ...    118.057865  124.202753    123.046225  119.167506   
3            15.0  ...    123.194562  114.003228    120.008496  117.029863   
4            10.0  ...    120.635543  102.842184    107.885445  114.996260   
...           ...  ...           ...         ...           ...         ...   
9505          9.0  ...    100.861731  112.689394    116.529573   97.537879   
9506         16.0  ...    116.832093  124.045802    134.408602  107.824427   
9507          8.0  ...     90.725806  114.535610    100.806452  103.082049   
9508         12.0  ...    106.913756  124.955052    123.841768  107.874865   
9509          9.0  ...    109.676097  111.704231    115.826158  105.773033   

      visitor_turn_over_ratio  home_turn_over_ratio  visitor_efg%  home_efg%  \
0                   12.845215             12.030075      0.631579   0.482558   
1                   12.026033             12.511730      0.446237   0.539474   
2                    8.419533              6.741848      0.552381   0.547170   
3                    5.461923              8.585701      0.601124   0.539326   
4                   15.332944             11.682243      0.623377   0.477273   
...                       ...                   ...           ...        ...   
9505                 9.344451             11.921459      0.605882   0.473958   
9506                 7.816941              9.572901      0.681818   0.545977   
9507                10.842627             16.523463      0.516854   0.606667   
9508                 8.112831              8.903587      0.627660   0.530000   
9509                12.540572             14.268549      0.541667   0.565476   

      visitor_ts%  home_ts%  
0        0.658503  0.494845  
1        0.483425  0.603095  
2        0.585422  0.600844  
3        0.609500  0.570016  
4        0.668769  0.534188  
...           ...       ...  
9505     0.541421  0.579922  
9506     0.602860  0.678497  
9507     0.499395  0.670405  
9508     0.581170  0.636214

In [44]:
df.isnull().sum()

date                    0
visitor_points          0
home_points             0
visitor_fgm             0
visitor_fga             0
                       ..
home_turn_over_ratio    1
visitor_efg%            1
home_efg%               1
visitor_ts%             0
home_ts%                0
Length: 62, dtype: int64

In [45]:
df = df.dropna()

In [46]:
# Create first target column 'winner'
df['home_win'] = df.apply(
    lambda row: 1 if row['home_points'] > row['visitor_points'] else 0,
    axis=1
)
# Create second target column 'total_points'
df['total_points'] = df['home_points'] + df['visitor_points']

# Display
df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_10980\3911342885.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['home_win'] = df.apply(
C:\Users\User\AppData\Local\Temp\ipykernel_10980\3911342885.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_points'] = df['home_points'] + df['visitor_points']


date  visitor_points  home_points  visitor_fgm  \
0  2018-01-01 00:00:00+00:00           114.0         96.0         41.0   
1  2018-01-01 00:00:00+00:00            98.0        106.0         36.0   
2  2018-01-01 00:00:00+00:00           142.0        148.0         53.0   
3  2018-01-01 00:00:00+00:00           116.0        113.0         46.0   
4  2018-01-01 01:00:00+00:00           123.0        110.0         43.0   

   visitor_fga  visitor_fgp  visitor_ftm  visitor_fta  visitor_ftp  \
0         76.0        0.539         18.0         24.0        0.750   
1         93.0        0.387         15.0         19.0        0.789   
2        105.0        0.505         26.0         37.0        0.703   
3         89.0        0.517          9.0         14.0        0.643   
4         77.0        0.558         27.0         34.0        0.794   

   visitor_tpm  ...  visitor_DRtg   home_DRtg  visitor_turn_over_ratio  \
0         14.0  ...     99.420050  112.871287                12.845215   
1         11.0  ...    102.554180  100.122599                12.026033   
2         10.0  ...    123.046225  119.167506                 8.419533   
3         15.0  ...    120.008496  117.029863                 5.461923   
4         10.0  ...    107.885445  114.996260                15.332944   

   home_turn_over_ratio  visitor_efg%  home_efg%  visitor_ts%  home_ts%  \
0             12.030075      0.631579   0.482558     0.658503  0.494845   
1             12.511730      0.446237   0.539474     0.483425  0.603095   
2              6.741848      0.552381   0.547170     0.585422  0.600844   
3              8.585701      0.601124   0.539326     0.609500  0.570016   
4             11.682243      0.623377   0.477273     0.668769  0.534188   

   home_win  total_points  
0         0         210.0  
1         1         204.0  
2         1         290.0  
3         0         229.0  
4         0         233.0  

[5 rows x 64 columns]

In [47]:
# Apply one-hot encoding and convert to booleans to integers
encoded_df = pd.get_dummies(df, columns=['visitor_team', 'home_team'])

# Display
new_df = encoded_df.replace({True: 1, False: 0})
new_df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_10980\525790992.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = encoded_df.replace({True: 1, False: 0})


date  visitor_points  home_points  visitor_fgm  \
0  2018-01-01 00:00:00+00:00           114.0         96.0         41.0   
1  2018-01-01 00:00:00+00:00            98.0        106.0         36.0   
2  2018-01-01 00:00:00+00:00           142.0        148.0         53.0   
3  2018-01-01 00:00:00+00:00           116.0        113.0         46.0   
4  2018-01-01 01:00:00+00:00           123.0        110.0         43.0   

   visitor_fga  visitor_fgp  visitor_ftm  visitor_fta  visitor_ftp  \
0         76.0        0.539         18.0         24.0        0.750   
1         93.0        0.387         15.0         19.0        0.789   
2        105.0        0.505         26.0         37.0        0.703   
3         89.0        0.517          9.0         14.0        0.643   
4         77.0        0.558         27.0         34.0        0.794   

   visitor_tpm  ...  home_team_Oklahoma City Thunder  home_team_Orlando Magic  \
0         14.0  ...                                0                        0   
1         11.0  ...                                0                        0   
2         10.0  ...                                0                        0   
3         15.0  ...                                1                        0   
4         10.0  ...                                0                        0   

   home_team_Philadelphia 76ers  home_team_Phoenix Suns  \
0                             0                       0   
1                             0                       0   
2                             0                       0   
3                             0                       0   
4                             0                       1   

   home_team_Portland Trail Blazers  home_team_Sacramento Kings  \
0                                 0                           1   
1                                 0                           0   
2                                 0                           0   
3                                 0                           0   
4                                 0                           0   

   home_team_San Antonio Spurs  home_team_Toronto Raptors  \
0                            0                          0   
1                            0                          0   
2                            0                          0   
3                            0                          0   
4                            0                          0   

   home_team_Utah Jazz  home_team_Washington Wizards  
0                    0                             0  
1                    0                             0  
2                    0                             0  
3                    0                             0  
4                    0                             0  

[5 rows x 122 columns]

# Machine Learning

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

# Split Data
X = new_df.drop(columns=['home_win', 'total_points', 'date'])
y_winner = df['home_win']
y_total = df['total_points']

X_train, X_test, y_winner_train, y_winner_test = train_test_split(X, y_winner, test_size=0.2, random_state=42)
_, _, y_total_train, y_total_test = train_test_split(X, y_total, test_size=0.2, random_state=42)

# Train Models
clf = RandomForestClassifier()
clf_model = clf.fit(X_train, y_winner_train)

reg = RandomForestRegressor()
reg_model = reg.fit(X_train, y_total_train)

# Predictions
winner_prediction = clf_model.predict(X_test)
total_predictions = reg_model.predict(X_test)

In [23]:
winner_prediction

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [24]:
total_predictions

array([238.2 , 186.52, 225.89, ..., 200.59, 252.23, 226.73])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_winner_pred = clf_model.predict(X_test)
print(confusion_matrix(y_winner_test, y_winner_pred))
print(classification_report(y_winner_test, y_winner_pred))
print("Accuracy: ", accuracy_score(y_winner_test, y_winner_pred))

[[906  20]
 [  7 969]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       926
           1       0.98      0.99      0.99       976

    accuracy                           0.99      1902
   macro avg       0.99      0.99      0.99      1902
weighted avg       0.99      0.99      0.99      1902

Accuracy:  0.9858044164037855


In [26]:
from sklearn.metrics import mean_squared_error, r2_score

y_total_pred = reg_model.predict(X_test)
print("MSE: ", mean_squared_error(y_total_test, y_total_pred))
print("R2 Score: ", r2_score(y_total_test, y_total_pred))

MSE:  0.9948286540483704
R2 Score:  0.9978383695533788


In [34]:
# Input Teams
visitor_team = input("Enter Away Team: ")
home_team = input("Enter Home Team: ")

# Prepare Input Data
input_data = {col: 0 for col in X.columns}  # Initialize all columns with 0

# Set team-specific features
if f'home_team_{home_team}' in input_data:
    input_data[f'home_team_{home_team}'] = 1
if f'visitor_team_{visitor_team}' in input_data:
    input_data[f'visitor_team_{visitor_team}'] = 1

# For numeric features, use the mean (or other default values)
for col in X.select_dtypes(include=['float64', 'int64']).columns:
    input_data[col] = X[col].mean()

# Convert to DataFrame
input_df = pd.DataFrame([input_data])

# Predict Winner
predicted_winner = clf_model.predict(input_df)[0]
winning_team = home_team if predicted_winner == 1 else visitor_team

# Predict Total Points
predicted_total_points = reg_model.predict(input_df)[0]

# Display Results
print("Predicted Winner:", winning_team)

Predicted Winner: Utah Jazz


In [28]:
new_df['home_win'].value_counts(normalize=True)

home_win
1    0.517089
0    0.482911
Name: proportion, dtype: float64

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_winner_test, clf_model.predict(X_test))
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[906  20]
 [  7 969]]


In [ ]:
# from sklearn.model_selection import cross_val_score
# scores = cross_val_score(clf_model, X, y_winner, cv=5)
# print("Cross-Validation Scores:", scores)


KeyboardInterrupt: 